
---
 - name: Provision Jmeter Nodes
   local_action:
     module: ec2
     key_name: "{{ ec2_keypair }}"
     group_id: "{{ ec2_security_group }}"
     instance_type: "{{ ec2_instance_type }}"
     instance_profile_name: "{{ ec2_instance_profile_name }}"
     image: "{{ ec2_image }}"
     vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
     region: "{{ ec2_region }}"
     instance_tags: '{"Name":"{{ec2_tag_Name}}"}'
     assign_public_ip: yes
     user_data: "{{ ec2_user_data }}"
     wait: true
     count: "{{ ec2_count }}"
   register: ec2

 - add_host: name={{ item.private_ip }} 
   with_items: "{{ ec2.instances }}"

 - name: Wait for the instances to boot by checking the ssh port
   wait_for: host={{item.private_ip}} port=22 delay=60 timeout=320 state=started
   with_items: "{{ ec2.instances }}"
